### ISSUE TITLE
Question: negation for f64

### ISSUE THREAD

**Issue by wbthomason** [metadsl/egglog-python#32]
Thanks for the library! I've been trying to use `egglog` for some numerical code, and have run into the missing unary negation operator for `f64`. I've tried patching this in myself analogously to its implementation for `Rational`, but I only end up with an error `No matching primitive for: (neg f64)`.

Is there a more fundamental reason that negation is unsupported for `f64`? Could you help me figure out how to add this? Thanks!

**Comment by saulshanabrook** [comment]
Hey @wbthomason thanks for giving this a spin!

I believe the issue is that the upstream egglog library does not support negation yet for f64. I doubt this is due to an intentional choice, but just that they hadn't needed it yet.

Once it is added to egglog, we can add it here.

It can be added to the [`f64.rs` file](https://github.com/egraphs-good/egglog/blob/14a6fc6060c09541728ae460e0a92909fabf508f/src/sort/f64.rs#L29-L46) and a test can be added to ][`f64.egg`](https://github.com/egraphs-good/egglog/blob/main/tests/f64.egg).

**Comment by wbthomason** [comment]
Got it, thanks! I'll take a look at making a quick PR. If, in the meanwhile, I wanted to make a custom "float-like" type with negation support, would this be as easy as making a separate `class_` call on a class with `__neg__` defined, or do I still need the upstream support?

**Comment by saulshanabrook** [comment]
> Got it, thanks! I'll take a look at making a quick PR. If, in the meanwhile, I wanted to make a custom "float-like" type with negation support, would this be as easy as making a separate class_ call on a class with __neg__ defined, or do I still need the upstream support?


Yeah I believe that should work! Something like this (untested):


```python
@egraph.class_
class MyFloat(BaseExpr):
    def __init__(self, f: f64Like) -> None: ...
    def __add__(self, other: MyFloat) -> MyFloat: ...
    def __neg__(self) -> MyFloat: ...

x, y = vars_("x y", f64)
egraph.register(
    replace(MyFloat(x) + MyFloat(y)).with_(MyFloat(x - y)),
    replace(-MyFloat(x)).with_(MyFloat(f64(0) - x)),
)
```
